tasks:
- before: >
    echo $SSH_PRIVATE_KEY | base64 --decode >> ~/.ssh/gitpod_rsa &&
    echo $SSH_PRIVATE_KEY | base64 --decode >> ~/.ssh/gitpod_rsa.pub
    chmod 600 ~/.ssh/gitpod_rsa &&
    chmod 644 ~/.ssh/gitpod_rsa.pub
- init: >
    git clone git@github.com:zpthree/pulsar-conf.git ~/pulsar &&
    git clone git@github.com:zpthree/dotfiles.git ~/dotfiles