image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: ignore
  visibility: public
- port: 3306
  onOpen: ignore

tasks:
  - before: |
      gp await-port 3306
      sh ~/.dotfiles/base.sh
      sh ~/.dotfiles/workflow-php.sh
    command: |
      source ~/.dotfiles/post-build.sh
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
